lac:
  - "LAC"
  - "LAC/CI"
  - "LAC_begin"
  - "LAC_END"
  - "lac"
  - "Код LAC"
  - "LAC code"
  - "LAC идентификатор"
ci:
  - "CI"
  - "CID"
  - "CELL_ID"
  - "Cell ID"
  - "CELLID"
  - "ci"
  - "Код CI"
  - "CI code"
  - "Идентификатор ячейки"
date:
  - "Дата"
  - "Date"
  - "DATE"
  - "дата"
time:
  - "Время"
  - "Time"
  - "TIME"
  - "время"
address:
  - "Адрес"
  - "Address"
  - "ADDRESS"
  - "адрес"
  - "Местоположение"
  - "Место размещения (адрес)"
azimuth:
  - "Азимут"
  - "Azimuth"
  - "AZIMUTH"
  - "азимут"
  - "AZ"
  - "Азимут (град.)"
height:
  - "Высота"
  - "Height"
  - "HEIGHT"
  - "высота"
lat:
  - "lat"
  - "Lat"
  - "LAT"
  - "Широта"
  - "Latitude"
  - "LAT северная широта (WGS-84)"
lon:
  - "lon"
  - "Lon"
  - "LON"
  - "Долгота"
  - "Longitude"
  - "LON восточная долгота (WGS-84)"
